INSERT INTO CATEGORIA_PRODUCTO (ID_CATEGORIA_PRODUCTO,NOMBRE) values (1,'BEBIDAS');
INSERT INTO CATEGORIA_PRODUCTO (ID_CATEGORIA_PRODUCTO,NOMBRE) values (2,'MECATOS');
INSERT INTO CATEGORIA_PRODUCTO (ID_CATEGORIA_PRODUCTO,NOMBRE) values (3,'DULCES');
INSERT INTO CATEGORIA_PRODUCTO (ID_CATEGORIA_PRODUCTO,NOMBRE) values (4,'ARTICULO');

INSERT INTO Producto (ID_PRODUCTO,nombre,ID_CATEGORIA_PRODUCTO,estado) values (1,'COCA-COLA',1,'A');
INSERT INTO Producto (ID_PRODUCTO,nombre,ID_CATEGORIA_PRODUCTO,estado) values (2,'PAPITA',2,'A');
INSERT INTO Producto (ID_PRODUCTO,nombre,ID_CATEGORIA_PRODUCTO,estado) values (3,'CHOCOLATE',3,'A');
INSERT INTO Producto (ID_PRODUCTO,nombre,ID_CATEGORIA_PRODUCTO,estado) values (4,'PEPSI',1,'A');


INSERT INTO Usuario (IDUSUARIO,USERNAME,NOMBRE,APELLIDO,IDENTIFICACION,FECHA_CREACION) values (1,'juanjimenez','JUAN','JIMENEZ','123456',SYSDATE);
INSERT INTO Usuario (IDUSUARIO,USERNAME,NOMBRE,APELLIDO,IDENTIFICACION,FECHA_CREACION) values (2,'juanjimenez2','JUAN2','JIMENEZ2','123456',SYSDATE);
